# Generated by Django 5.0.1 on 2025-11-23 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('excerpt', models.TextField(help_text='Краткое описание для карточки новости (до 300 символов)', max_length=300, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Главное изображение')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Дополнительное изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Дополнительное изображение 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
