# Generated by Django 5.0.1 on 2025-11-23 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_start'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.AddField(
            model_name='news',
            name='date_end',
            field=models.DateField(blank=True, help_text='Оставьте пустым для одного дня', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Основная дата или начало периода', verbose_name='Дата начала'),
        ),
    ]
