# Generated by Django 5.0.1 on 2025-11-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_remove_news_date_news_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF файл (например, программу мероприятия, положение и т.д.)', null=True, upload_to='news_pdfs/', verbose_name='PDF документ'),
        ),
    ]
