# Generated by Django 5.0.1 on 2025-11-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pdf_title',
            field=models.CharField(blank=True, help_text='Например: "Правила кикбоксинга" или "Программа турнира"', max_length=200, verbose_name='Название PDF документа'),
        ),
    ]
